### ISSUE TITLE
define new upstream

### ISSUE THREAD

**Issue by simonschmeisser** [ubports/telepathy-ofono#4]
Since work on this code is no longer happening inside launchpad it would be great to agree on a new central follow-up location where we can do pull requests, peer review, releases, CI and finally success :)

I have no opinion if this location should be here or at https://github.com/TelepathyIM/telepathy-ofono

I opened an issue there as well https://github.com/TelepathyIM/telepathy-ofono/issues/3

@adamboardman please also feel invited to the party

**Comment by Kaffeine** [comment]
Hi here. I pushed the referenced repository.

I'm a Telepathy developer since 2014 (right after Collabora left the project).
I want to develop the project and I would accept the upstream to be here instead of TelepathyIM, especially because you have CI :) and we still have to set up such one in TpIM.

Back in January I asked @Flohack74 to add some kind of development branch here and in yet_not_existing `ofono-qt` repository so I'll make PRs (four fixes from my [tp-ofono repo](https://github.com/TelepathyIM/telepathy-ofono/commits/staging) and two fixes from my [ofono-qt fork](https://github.com/Kaffeine/libofono-qt/commits/master)).

I definitely want to collaborate with you and all other possible distributions, e.g. PostmarketOS / KDE Plasma and Sailfish OS (my commits actually needed to build on SFOS and some other systems).

I welcome and encourage all Telepathy Connection Managers developers to host at TelepathyIM because the projects will get more attention there. The TelepathyIM project is not distro- or DE- specific and it will be easier to manage all related stuff there (e.g. plan and manage tasks about bringing up a new TelepathyQt version (I actually ported this project to a new TpQt release once 58a1fefa99a73b0bec949d6305832773ac3c659d).

**Comment by Kaffeine** [comment]
Hm, I thought a bit more and realised that TelepathyIM and UBports are not going to fit each other needs.
For TelepathyIM we need a CI that will test the modern version of components. E.g. we'll need to test telepathy-ofono with a brand-new TelepathyQt with new API.
For UBports it is important to test the CM in the exact system environment with the exact package versions.

This way, I would say that conceptually the upstream should be at TelepathyIM and UBports repo is still needed as a distro-specific adoptation. :thinking:

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telepathy-ofono/-/issues/4
