### ISSUE TITLE
Visual Voicemail (VVM) not supported in Ubuntu Touch

### ISSUE THREAD

**Issue by noobpurple** [ubports/telepathy-ofono#8]
- Device: Nexus 5
- Channel: Stable
- Build: OTA-11

Whenever I receive or delete a voicemail, I get a text message. It shows up as Unknown Number, and tapping the message thread shows 'x-ofono-unknown' at the top. Each message starts with 'STATE?', 'MBOXUPDATE?', or 'vvm.mobile.att.net:5400?' and has a bunch of other url-query-like options. I only just got this device and set it up, so I can't say whether or not this is a recent development. My carrier is Cricket, which runs through ATT's network if I remember correctly.

**Comment by dobey** [comment]
Those messages are because Visual Voice Mail was enabled, which UT currently does not support. The right fix would be to add support for this to the system. Someone was looking into it once, but I guess never got to making PRs.

As a workaround, if you have another Android device available that will work on the network, you should be able to insert your SIM card in it, and go into the visual voicemail app, to disable visual voicemail, after which you should stop getting such SMSes.

**Comment by gber** [comment]
Migrated to https://gitlab.com/ubports/development/core/telepathy-ofono/-/issues/8
